import streamlit as st
from core.state import init_state
from ui.instructions import instructions_panel
from ui.run_panel import run_panel

st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()


init_state()

st.title("Parallel Exploration Tool for Risky Interactions")
st.caption(
    "Runs `inspect_ai.eval` in a background Python process and streams output here. "
    "This version removes instruction persistence and the transcript viewer."
)

instructions_panel()
run_panel()

st.divider()


from dashboard import audit_dashboard
dashboard_path = "/home/user1/experiments/petri-app/outputs/user1/run-20251014-144525"
audit_dashboard(dashboard_path)



# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')